import type { Developer } from "./common";
import avatarData from "./bluesky.json";

// Generated by scripts/fetch-bluesky.mjs (runs before `npm run dev` / `npm run build`)
const avatars = avatarData as Record<string, string>;

// Developers without a logoUrl get their current Bluesky profile picture
export function withBlueskyAvatar(dev: Developer): Developer {
  if (dev.logoUrl || !dev.links.bluesky) return dev;
  const handle = dev.links.bluesky.split("/profile/")[1]?.toLowerCase();
  return { ...dev, logoUrl: handle && avatars[handle] };
}
