import type { Game, ReleaseDate } from "./common";
import steamData from "./steam.json";

// Generated by scripts/fetch-steam.mjs (runs before `npm run dev` / `npm run build`)
type SteamInfo = {
  capsuleUrl?: string;
  posterUrl?: string;
  iconUrl?: string;
  description?: string;
  release?: ReleaseDate;
};
const steam = steamData as Record<string, SteamInfo>;

// Steam's current images, description and release date override the manual values when available
export function withSteam(game: Game): Game {
  const appId = game.store.steam?.match(/\/app\/(\d+)/)?.[1];
  const info = appId ? steam[appId] : undefined;
  if (!info) return game;
  return {
    ...game,
    imageUrl: info.posterUrl ?? game.imageUrl,
    capsuleUrl: info.capsuleUrl,
    iconUrl: info.iconUrl,
    description: info.description || game.description,
    release: info.release ?? game.release,
  };
}
